# Practical session 3 - Practice with numpy

Course: [SDIA-Python](https://github.com/guilgautier/sdia-python)

Date: 10/06/2021

Instructor: [Guillaume Gautier](https://guilgautier.github.io/)

Students (pair):
- [Student 1]([link](https://github.com/username1))
- [Student 2]([link](https://github.com/username2))

In [2]:
%load_ext autoreload
%autoreload 2

import numpy as np
from sdia_python.lab2.utils import get_random_number_generator

In [3]:
my_array = np.array([0])
print(type(my_array))
dir(np.ndarray)

<class 'numpy.ndarray'>


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

Propose at leat 2 ways to create an integer vector of size 100 made of 1s

In [4]:
vector1 = np.ones((100,), dtype=int)

In [5]:
vector1 = np.zeros((100,), dtype = int )
for i in range (100):
    vector1[i] = 1


Create a vector with values ranging from 10 to 49

In [6]:
vector2 = np.arange(10,50)

Propose a way to construct the vector $(0.0, 0.2, 0.4, 0.6, 0.8)$

In [7]:
vector3 = np.array([0.0 , 0.2 , 0.4 , 0.6 , 0.8])
vector3 = np.linspace(0.0 , 1.0 , 6 , endpoint=False)
vector3 = np.arange(0.0 , 1.0 , 0.2)

Convert a float array into an integer array in place

In [8]:
vector4 = np.array([0.0 , 2.0 , 4.0 , 6.0 , 8.0])
vector4.astype(int)
print(vector4)

[0. 2. 4. 6. 8.]


Given a boolean array

- return the indices where 
- negate the array inplace? 

In [9]:
sample_arr = [True, False]
bool_arr = np.random.choice(sample_arr, size=10)
L = np.where(bool_arr == True)
print(L)

(array([2, 6], dtype=int64),)


In [10]:
sample_arr = np.array([True, False])
bool_arr = np.random.choice(sample_arr, size=10)
np.invert(bool_arr)

array([ True, False,  True, False,  True, False, False,  True,  True,
       False])

Given 2 vectors $u, v$, propose at least

- 2 ways to compute the inner product $v^{\top} u$ (here they must have the same size)
- 2 ways to compute the outer product matrix $u v^{\top}$
- 2 ways to compute the outer sum matrix "$M = u + v^{\top}$", where $M_{ij} = u_i + v_j$

In [11]:
u = np.random.randint(1,5 , size=5)
v = np.random.randint(1,5, size = 5)
print(np.dot(v,u))
ps = 0
for i in range(5):
    ps += u[i]*v[i] 
print(ps)


28
28


In [12]:
u = np.random.randint(1,5 , size=5)
v = np.random.randint(1,5, size = 5)
outer_matrix = np.zeros((5,5))
for i in range(5):
    for j in range(5):
        outer_matrix[i][j] = u[i]*v[j]
print(outer_matrix)
u = np.reshape(u, (5,1))
v = np.reshape(v, (5,1))
print(np.dot(u,v.T))

[[ 9.  3.  9.  3.  6.]
 [12.  4. 12.  4.  8.]
 [ 6.  2.  6.  2.  4.]
 [ 3.  1.  3.  1.  2.]
 [12.  4. 12.  4.  8.]]
[[ 9  3  9  3  6]
 [12  4 12  4  8]
 [ 6  2  6  2  4]
 [ 3  1  3  1  2]
 [12  4 12  4  8]]


In [13]:
u = np.random.randint(1 , 5 , size=5)
v = np.random.randint(1, 5, size = 5)
M = np.zeros((5,5))
for i in range(5):
    for j in range(5):
        M[i][j] = u[i]+v[j]
print(u)
print(v)
print(M)
I = np.ones(5)
A = np.outer(u,I)
B = np.outer(I,v)
print(A+B)

[3 2 2 2 2]
[4 2 2 2 4]
[[7. 5. 5. 5. 7.]
 [6. 4. 4. 4. 6.]
 [6. 4. 4. 4. 6.]
 [6. 4. 4. 4. 6.]
 [6. 4. 4. 4. 6.]]
[[7. 5. 5. 5. 7.]
 [6. 4. 4. 4. 6.]
 [6. 4. 4. 4. 6.]
 [6. 4. 4. 4. 6.]
 [6. 4. 4. 4. 6.]]


Given the following matrix

$$
M = 
\begin{pmatrix}
    0 & 1 & 2 \\
    3 & 4 & 5 \\
    6 & 7 & 8 \\
\end{pmatrix}
$$

- Create $M$ using as a list of lists and access the element in the middle
- Propose at least 2 ways to create $M$ using numpy and access the element in the middle
- Swap its first and second row
- Propose at least 3 ways to extract the submatrix $\begin{pmatrix}4 & 5 \\7 & 8 \\\end{pmatrix}$
- Propose at least 2 ways to extract the diagonal of $M$
- Propose at least 2 ways to compute $M^3$
- Compute $v^{\top} M$, resp. $M N$ for a vector, resp. a matrix of your choice. 
- Propose 2 ways to "vectorize" the matrix, i.e., transform it into
  - $(0, 1, 2, 3, 4, 5, 6, 7, 8)$
  - $(0, 3, 6, 1, 4, 7, 2, 5, 8)$
- Consider $v = (1, 2 , 3)$, compute the
  - row-wise multiplication of $M$ by $v$ ($M_{i\cdot}$ is multiplied by $v_i$)
  - column-wise multiplication of $M$ by $v$ ($M_{\cdot j}$ is multiplied by $v_i$)

In [14]:
M = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
M = np.arange(0,9 ,1)
M = M.reshape(3,3)
print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
M[1][1]

4

In [17]:
H = M.copy()
H[1], H[2] = H[2],M[1]
print(H)

[[0 1 2]
 [6 7 8]
 [3 4 5]]


In [18]:
M[1:,1:]

array([[4, 5],
       [7, 8]])

In [19]:
M[np.ix_([1,2],[1,2])]

array([[4, 5],
       [7, 8]])

In [20]:
B = np.array (M[i][i] for i in range(0,3))
print(B)

<generator object <genexpr> at 0x000001EA5936EF90>


Write a function `is_symmetric` that checks whether a given n x n matrix is symmetric, and provide an example

## Random

REQUIREMENT: USE THE FUNCTION `get_random_number_generator` as previously used in Lab 2.

Consider the Bernoulli(0.4) distribution

- Propose at least 2 ways to generate n=1000 samples from it
- Compute the empirical mean and variance

Consider a random matrix of size $50 \times 100$, filled with i.i.d. standard Gaussian variables, compute

- the absolute value of each entry
- the sum of each row
- the sum of each colomn 
- the (euclidean) norm of each row
- the (euclidean) norm of each column